# 2b Vectorized operations

## 2b.1 What is vectorization?

Vectorizatipon is applying the same operation to every element within an array, or multiple arrays. Numpy performs vectorized operations much faster and utilizing less memory (in most cases) than iterating through each element in a for loop. Vectorized operations are essential to linear algebra, which form the basis of machine learning, data mining, and processing.

## Exercise 2b.1

Don't forget to import numpy

In [1]:
import numpy

## 2b.2 Examples of how vectorization of a single array can be utilized:

Mathematical functions, scalar transformations, other transformations, boolean operations

### 2b.2.1 Mathematical functions applied to vectors

Numpy has a huge list of mathematical functions can be applied to arrays. These operations are vectorized and thus applied elementwise. Some examples are:

- numpy.sqrt(x): square root
- numpy.sin(x): sine
- numpy.cos(x): cosine
- numpy.tan(x): tangent
- numpy.exp(x): exponential
- numpy.log(x): natural logarithm
- numpy.round(x, decimals = 2 ) : round to the nearest integer (check the type!)
- numpy.floor(x): round down to an integer
- numpy.ceil(x): round up to an integer

In [2]:
x = numpy.array([1, 2, 3, 4])
print("x = ", x)
print("sqrt(x) = ", numpy.sqrt(x))
print("sin(x) = ", numpy.sin(x) )
print("cos(x) = ", numpy.cos(x) )
print("tan(x) = ", numpy.tan(x) )
print("exp(x) = ", numpy.exp(x) )
print("log(x) = ", numpy.log(x) )

x =  [1 2 3 4]
sqrt(x) =  [ 1.          1.41421356  1.73205081  2.        ]
sin(x) =  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
cos(x) =  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
tan(x) =  [ 1.55740772 -2.18503986 -0.14254654  1.15782128]
exp(x) =  [  2.71828183   7.3890561   20.08553692  54.59815003]
log(x) =  [ 0.          0.69314718  1.09861229  1.38629436]


In [3]:
# rounding 
x = 10*numpy.random.random((2,5))
print("not rounded:", x)
x1 = numpy.round(x, decimals = 2)
print("round:", x1)
x2 = numpy.floor(x)
print("floor:", x2)
x3 = numpy.ceil(x)
print("ceil:", x3)

not rounded: [[ 1.37341699  6.3141477   1.80235171  2.23837993  0.58047243]
 [ 3.12976912  7.66781054  4.39066393  0.34977829  3.19737225]]
round: [[ 1.37  6.31  1.8   2.24  0.58]
 [ 3.13  7.67  4.39  0.35  3.2 ]]
floor: [[ 1.  6.  1.  2.  0.]
 [ 3.  7.  4.  0.  3.]]
ceil: [[ 2.  7.  2.  3.  1.]
 [ 4.  8.  5.  1.  4.]]


### 2b.2.2 Simple scalar transformations

Simple mathematical operations can be performed between an array (of any dimensionality) and a scalar value:

In [4]:
# 1 dimensional
x = numpy.array([20, 25, 30, 35])
print("x - 2 = ", x - 2)
print("x * 2 = ", x * 2)
print("x **2 = ", x**2)

x - 2 =  [18 23 28 33]
x * 2 =  [40 50 60 70]
x **2 =  [ 400  625  900 1225]


In [5]:
# N dimensional
x = numpy.arange(0, 2**3).reshape(2,2,2)
print( x )
print( "x **2 = \n", x**2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
x **2 = 
 [[[ 0  1]
  [ 4  9]]

 [[16 25]
  [36 49]]]


### 2b.2.3 Boolean operations on arrays

As we've seen before, Boolean conditions can be applied to every element in an array. This is also a vectorized function. 

Several different conditions can be used, such as: equal to (==), not equal to (!=), greater than (>= or >), or smaller than (<= or <). 

In [6]:
# boolean operations on arrays
x = numpy.array([10, 20, 30, 14, 15, 16])
y = numpy.array([7, 5, 5, 7, 5, 7]) 
print("(x > 15) = ", x>15)
print("(y == 7) = ", y==7)

(x > 15) =  [False  True  True False False  True]
(y == 7) =  [ True False False  True False  True]


### 2b.2.4 Other vectorized tranformations

Numpy provides other functions that perform vectorized operations across arrays that are not traditional mathematical functions but can be very useful. For example:

- numpy.cumsum(x): returns an array containing the cumulative sum of the original elements
- numpy.cumsum(x): returns an array containing the cumulative propduct of the original elements
- numpy.diff(x): returns an array containing the difference between each subsequent element (changes the number of items!)


In [7]:
x = numpy.array([1, 4, 7, 2])
print( x )
print( numpy.cumsum(x) )
print( numpy.cumprod(x) )
print( numpy.diff(x) )


[1 4 7 2]
[ 1  5 12 14]
[ 1  4 28 56]
[ 3  3 -5]


### 2b.2.5 More complex transformations

Mathematical opertions on vectors can be combined to transform all values in the vector. Many of these transformations are very common in machine learning and can be efficiently implemented using vectorized operations. For example:

- Standardization: `z = (x - mean(x)) / stdev(x)`. Standardized values (z-scores) have zero mean and unit standard deviation. Standardization is often used before applying machine learning algorithms. 

- Feature scaling: `y = (x - min(x)) / (max(x) - min(x))`, this brings the score in the range 0 to 1.

- Convertion between different scales of measurements. Some examples: from Fahrenheit to Celsius, or from Dollars to Euros, or from Inches to Centimetres. 

## Exercise 2b.2

- Define function `to_cm` which takes a vector of measurements in inches and converts them to centimeters.
- Define function `to_celsius` which takes a vector of measurements in Fahrenheit and converts them to Celsius: C = (F-32)/1.8


In [8]:
def to_cm(x):
    return ...

In [9]:
def to_celsius(x):
    return ...

## 2b.3 Vectorized dimension reduction

We have already seen some functions that reduce the dimensionality of an array. For example sum takes as input an array and returns a single value.

In [10]:
print( numpy.sum(numpy.array([10, 20, 30])) )

60


Many functions that reduce the number of dimensions can be also applied to a specific subset of dimensions. These functions have an optional parameter which is called `axis`. If no value for `axis` is provided (as is the case above) then the function is applied to the whole array. When `axis=0` then the function is applied to each column and the value for each column is returned. When `axis=1` then the function is applied to each row. The same logic applies in higher dimensions. For example, these functions all take an optional axis parameter:

- numpy.sum(x)
- numpy.min(x)
- numpy.argmin()
- numpy.max()
- numpy.argmax()
- numpy.median(x)
- numpy.mean(x)
- numpy.average(x, axis= , weights= ) : (weighted) average
- numpy.std(x) : standard deviation
- numpy.var(x) : variance

In [11]:
x = numpy.array([[1, 6, 5], [2, 7, 8]])

# functions applied to the entire array:
print("sum:", x.sum())
print("minimum:", x.min(), "and index of minimum:", x.argmin())
print("maximum:", x.max(), "and index of maximum:", x.argmax())

sum: 29
minimum: 1 and index of minimum: 0
maximum: 8 and index of maximum: 5


In [12]:
# functions applied to only one dimension of the array:
print("column sums:", x.sum(axis=0))
print("row sums:", x.sum(axis=1))
print("minimum per column:", x.min(axis=0))
print("maximum per row:", x.max(axis=1))

column sums: [ 3 13 13]
row sums: [12 17]
minimum per column: [1 6 5]
maximum per row: [6 8]


Many similar functions exist which ignore NAN. These functions are called: `nanmedian`, `nanmean`, `nanstd`, `nanvar`, etc. For more statistical functions in numpy: http://docs.scipy.org/doc/numpy/reference/routines.statistics.html

## Exercise 2b.3

The function `softmax` is often used in machine learning and statistics to convert a vector of arbitrary numbers into a vector of probabilities summing up to 1. Softmax is computed by computing the exponential of each number, and then dividing each number by the sum of the exponentials:

$$ \mathrm{softmax}(x_i): \frac{\exp(x_i)}{\sum_{k=1}^N \exp(x_k)} $$

Implement the softmax function. Verify that in the resulting vector all number are between 0 and 1. Verify that the resulting numbers sum up to $1$. Try implementing a version that relies on for loops and a version that is vectorized.



In [13]:
# assume a one-dimensional array
def softmax(x):
    return ...

In [14]:
def for_loop_softmax(x):
    return ...

In [15]:
# try without assuming x is only one dimension
# if axis is 0, compute the softmax for each column,
# if axis is 1, compute the softmax for each row, etc.
# you can assume axis is less than or equal to the number of dimensions
def softmax_axis(x, axis=0):
    return ...

## 2b.4 Vectorized operations on multiple arrays 

Just as many functions can be applied to a single array, there are other functions that perform vectorized operations on multiple arrays. In this section we will review two classes of functions defined by the relationship between the arrays.


### 2b.4.1 Arrays of the same shape

The most basic of these functions are the standard mathematical operations: addition, subtraction, multiplication, division and power.



In [16]:
x = numpy.array([10, 20, 30, 40])
y = numpy.array([5, 7, 52, 34])

print("y - x = ", y - x)
print("x + y = ", x + y)
print("x * y = ", x * y)
print("x / y = ", x / y)

y - x =  [ -5 -13  22  -6]
x + y =  [15 27 82 74]
x * y =  [  50  140 1560 1360]
x / y =  [ 2.          2.85714286  0.57692308  1.17647059]


These vectorized functions also work for matricies and N-dimensional arrays of the same size.

In [17]:
x = numpy.array([[10, 20, 25], [30, 40, 50]])
y = numpy.array([[5, 7, 10], [52, 34, 17]])

print(y - x)
print(x + y)
print(x * y)
print(x / y)

[[ -5 -13 -15]
 [ 22  -6 -33]]
[[15 27 35]
 [82 74 67]]
[[  50  140  250]
 [1560 1360  850]]
[[ 2.          2.85714286  2.5       ]
 [ 0.57692308  1.17647059  2.94117647]]


## 2b.4.2 Arrays with different shapes

Besides operations between arrays of the same shape, it is sometimes possible to perform operations between arrays of different shapes. In numpy performing vectorized operations on arrays with different shapes is called broadcasting.

We've already looked at the most common form of broadcasting: operations that involve an array and a single element. For example:

In [18]:
print( numpy.array([3,4])**3 )

[27 64]


Other combinations are possible and important for linear algebra, statistics, and machine learning. 

- Operations can occur between an array and a row vector if the number of columns in the array is the same as the length of the row vector.

In [19]:
# operations between array and vector
x = numpy.array([[1, 2, 3], [4, 5, 6]])
y = numpy.array([5, 5, 5]) # row vector

print("x + y = \n", x+y)
print("x * y = \n", x*y)

x + y = 
 [[ 6  7  8]
 [ 9 10 11]]
x * y = 
 [[ 5 10 15]
 [20 25 30]]


- Operations can also occur between an array and a column vector if the number of rows in the array is the same as the length of the column vector.

In [20]:
# operations between array and vector
x = numpy.array([[1, 2, 3], [4, 5, 6]])
z = numpy.array([[1], [2]]) # column vector

print("x + z = \n", x+z)
print("x * z = \n", x*z)

x + z = 
 [[2 3 4]
 [6 7 8]]
x * z = 
 [[ 1  2  3]
 [ 8 10 12]]


Broadcasting between two multidimensional arrays of different sizes can be done but is complex. Numpy is smart about figuring out if two arrays can be aligned such that dimensions have the same number of elements to perform the desired operation. 

Often, however, this can result in unexpected behavior that does not produce an error if arrays are not the dimensionality you expect. Because of this, it is important to confirm the dimensionality of arrays match your expectations throughout your analysis. For more information about Broadcasting:
http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

## Exercise 2b.4

Generate a numpy array of length 5 containing random integers between 1 and 15. Use the functions `numpy.reshape`, `numpy.ones` and broadcasting to build a two-dimensional array where each element (i, j) is the product of the ith and jth elements of the initial array.